----------------------------------------------------------------
Tue Jul 19 13:32:29 PDT 2016:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance a816c00e-0156-04dc-1c66-00000e4d68c8 
on database directory /Users/julianrobichaux/Documents/workspace/jdbc/JdbcTest/test.db with class loader sun.misc.Launcher$AppClassLoader@4554617c 
Loaded from file:/Users/julianrobichaux/Documents/workspace/jdbc/JdbcTest/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_92-b14
user.dir=/Users/julianrobichaux/Documents/workspace/jdbc/JdbcTest
os.name=Mac OS X
os.arch=x86_64
os.version=10.10.5
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Tue Jul 19 13:32:29 PDT 2016:
Shutting down instance a816c00e-0156-04dc-1c66-00000e4d68c8 on database directory /Users/julianrobichaux/Documents/workspace/jdbc/JdbcTest/test.db with class loader sun.misc.Launcher$AppClassLoader@4554617c 
Tue Jul 19 13:32:29 PDT 2016 Thread[main,5,main] Cleanup action starting
java.sql.SQLException: Database 'test.db' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at com.example.jdbc.DatabaseTest.closeDatabaseConnection(DatabaseTest.java:196)
	at com.example.jdbc.DatabaseTest.testConnection(DatabaseTest.java:222)
	at com.example.jdbc.DatabaseTest.main(DatabaseTest.java:66)
Caused by: ERROR XJ004: Database 'test.db' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 19 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'test.db' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at com.example.jdbc.DatabaseTest.closeDatabaseConnection(DatabaseTest.java:196)
	at com.example.jdbc.DatabaseTest.testConnection(DatabaseTest.java:222)
	at com.example.jdbc.DatabaseTest.main(DatabaseTest.java:66)
============= end nested exception, level (1) ===========
Cleanup action completed
